
import java.math.BigDecimal;


/*
 *Universidad del Valle de Guatemala
 * Algoritmos y estructuras de datos
 * Hoja de Trabajo # 1 
 * Diego Bran 08068
 * Nombre#
 * Nombre#
 */
public class Frame_Radio extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Radio
     */
    public Frame_Radio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        despliegue = new javax.swing.JTextField();
        retro = new javax.swing.JButton();
        adelantar = new javax.swing.JButton();
        salvar1 = new javax.swing.JButton();
        salvar2 = new javax.swing.JButton();
        salvar3 = new javax.swing.JButton();
        salvar4 = new javax.swing.JButton();
        salvar5 = new javax.swing.JButton();
        salvar6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        desp3 = new javax.swing.JButton();
        desp6 = new javax.swing.JButton();
        desp1 = new javax.swing.JButton();
        desp2 = new javax.swing.JButton();
        desp5 = new javax.swing.JButton();
        desp4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cambioBanda = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        despliegue.setBackground(new java.awt.Color(0, 0, 0));
        despliegue.setEditable(false);
        despliegue.setForeground(new java.awt.Color(0, 255, 51));

        retro.setText("<");
        retro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retroActionPerformed(evt);
            }
        });

        adelantar.setText(">");
        adelantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelantarActionPerformed(evt);
            }
        });

        salvar1.setText("1");
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        salvar2.setText("2");
        salvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar2ActionPerformed(evt);
            }
        });

        salvar3.setText("3");
        salvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar3ActionPerformed(evt);
            }
        });

        salvar4.setText("4");
        salvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar4ActionPerformed(evt);
            }
        });

        salvar5.setText("5");
        salvar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar5ActionPerformed(evt);
            }
        });

        salvar6.setText("6");
        salvar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar6ActionPerformed(evt);
            }
        });

        label.setText("Emisora:");

        label2.setText("Estación Guardada:");

        desp3.setText("3");
        desp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp3ActionPerformed(evt);
            }
        });

        desp6.setText("6");
        desp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp6ActionPerformed(evt);
            }
        });

        desp1.setText("1");
        desp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp1ActionPerformed(evt);
            }
        });

        desp2.setText("2");
        desp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp2ActionPerformed(evt);
            }
        });

        desp5.setText("5");
        desp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp5ActionPerformed(evt);
            }
        });

        desp4.setText("4");
        desp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desp4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Guardar");

        jLabel3.setText("Desplegar");

        cambioBanda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "FM" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(desp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(desp2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(desp3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(desp4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(desp5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(desp6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel3))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(layout.createSequentialGroup()
                                    .add(salvar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(salvar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(salvar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(salvar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(salvar5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(salvar6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(label)
                                        .add(retro))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(adelantar)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(label2))
                                        .add(layout.createSequentialGroup()
                                            .add(despliegue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .add(layout.createSequentialGroup()
                                .add(223, 223, 223)
                                .add(jLabel1)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel2))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(cambioBanda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(despliegue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1)
                            .add(label)))
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(cambioBanda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(retro)
                    .add(adelantar)
                    .add(label2))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(salvar1)
                    .add(salvar2)
                    .add(salvar3)
                    .add(salvar4)
                    .add(salvar5)
                    .add(salvar6)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(desp1)
                    .add(desp2)
                    .add(desp3)
                    .add(desp4)
                    .add(desp5)
                    .add(desp6)
                    .add(jLabel3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adelantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelantarActionPerformed
        
        
        int a = cambioBanda.getSelectedIndex();
       
        if (a == 0) {
        //Incrementa un int cada vez que se da un click en la variable incrementar la frecuencia del radio
        temporalAM++; 
        despliegue.setText(""+temporalAM);
        
        
        }else if (a == 1)
            
        {
        
             temporalFM = temporalFM + suma;
            despliegue.setText(""+temporalFM);
        }
        
     
        
     
    }//GEN-LAST:event_adelantarActionPerformed

    private void retroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retroActionPerformed
        // TODO add your handling code here:
       
        
        int retroB = cambioBanda.getSelectedIndex(); 
        
        if(retroB == 0){
        
        temporalAM--; 
        despliegue.setText(""+temporalAM);
        
        }else if (retroB == 1)
            
        {
        
            
            
        temporalFM = temporalFM - suma; 
        despliegue.setText(""+temporalFM);
        }
            
    }//GEN-LAST:event_retroActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        // TODO add your handling code here:
        salvarE1 = despliegue.getText();
        
        
    }//GEN-LAST:event_salvar1ActionPerformed

    private void desp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp1ActionPerformed
        // TODO add your handling code here:
        
       label2.setText("Estación Guardada:"+salvarE1); 
        
        
    }//GEN-LAST:event_desp1ActionPerformed

    private void salvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar2ActionPerformed
        // TODO add your handling code here:
        
        salvarE2 = despliegue.getText();
    }//GEN-LAST:event_salvar2ActionPerformed

    private void desp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp2ActionPerformed
        // TODO add your handling code here:
        
        label2.setText("Estación Guardada:"+salvarE2); 
    }//GEN-LAST:event_desp2ActionPerformed

    private void salvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar3ActionPerformed
        // TODO add your handling code here:
        
        salvarE3 = despliegue.getText();
    }//GEN-LAST:event_salvar3ActionPerformed

    private void desp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp3ActionPerformed
        // TODO add your handling code here:
        
        label2.setText("Estación Guardada:"+salvarE3); 
    }//GEN-LAST:event_desp3ActionPerformed

    private void salvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar4ActionPerformed
        // TODO add your handling code here:
        
        salvarE4 = despliegue.getText();
        
    }//GEN-LAST:event_salvar4ActionPerformed

    private void desp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp4ActionPerformed
        // TODO add your handling code here:
        
        label2.setText("Estación Guardada:"+salvarE4); 
    }//GEN-LAST:event_desp4ActionPerformed

    private void salvar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar5ActionPerformed
        // TODO add your handling code here:
        
        salvarE5 = despliegue.getText();
        
    }//GEN-LAST:event_salvar5ActionPerformed

    private void desp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp5ActionPerformed
        // TODO add your handling code here:
        label2.setText("Estación Guardada:"+salvarE5); 
        
    }//GEN-LAST:event_desp5ActionPerformed

    private void salvar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar6ActionPerformed
        // TODO add your handling code here:
        salvarE6 = despliegue.getText();
        
    }//GEN-LAST:event_salvar6ActionPerformed

    private void desp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desp6ActionPerformed
        // TODO add your handling code here:
        
        label2.setText("Estación Guardada:"+salvarE6); 
    }//GEN-LAST:event_desp6ActionPerformed

   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame_Radio().setVisible(true);
            }
        });
        
        
       
        
    
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelantar;
    private javax.swing.JComboBox cambioBanda;
    private javax.swing.JButton desp1;
    private javax.swing.JButton desp2;
    private javax.swing.JButton desp3;
    private javax.swing.JButton desp4;
    private javax.swing.JButton desp5;
    private javax.swing.JButton desp6;
    private javax.swing.JTextField despliegue;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JButton retro;
    private javax.swing.JButton salvar1;
    private javax.swing.JButton salvar2;
    private javax.swing.JButton salvar3;
    private javax.swing.JButton salvar4;
    private javax.swing.JButton salvar5;
    private javax.swing.JButton salvar6;
    // End of variables declaration//GEN-END:variables
    public static final int AM_MIN = 535; 
    public static final int AM_MAX = 1600; 
    public static final double FM_MIN = 88;
    public static final double FM_MAX = 108;  
    int temporalAM = AM_MIN; 
    double temporalFM = FM_MIN;
    double suma = 0.6;
    String salvarE1;
    String salvarE2;
    String salvarE3;
    String salvarE4;
    String salvarE5;
    String salvarE6; 
    
    


}
